# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [IAM3, IAB]
patreon: # Replace with a single Patreon username mouse36872
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username Snaker.io 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username TELIANET
issuehunt: # Replace with a single IssueHunt username Barbie
otechie: # Replace with a single Otechie username yankie doodle 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://ipinfo.io/AS1299','https://ultra.com','https://pink.com']
